### ISSUE TITLE
Decoders shape is changing

### ISSUE THREAD

**Issue by ManikandanThangavelu** [ankonzoid/artificio#12]
Im getting the below error when I try to fit the model.

ValueError: A target array with shape (73, 458, 690, 3) was passed for an output of shape (None, 460, 692, 3) while using as loss `binary_crossentropy`. This loss expects targets to have the same shape as the output.

The summary of the autoencoder is,

autoencoder.summary():
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         (None, 458, 690, 3)       0         
_________________________________________________________________
conv2d (Conv2D)              (None, 458, 690, 16)      448       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 229, 345, 16)      0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 229, 345, 8)       1160      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 115, 173, 8)       0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 115, 173, 8)       584       
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 58, 87, 8)         0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 58, 87, 8)         584       
_________________________________________________________________
up_sampling2d (UpSampling2D) (None, 116, 174, 8)       0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 116, 174, 8)       584       
_________________________________________________________________
up_sampling2d_1 (UpSampling2 (None, 232, 348, 8)       0         
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 230, 346, 16)      1168      
_________________________________________________________________
up_sampling2d_2 (UpSampling2 (None, 460, 692, 16)      0         
_________________________________________________________________
conv2d_6 (Conv2D)            (None, 460, 692, 3)       435       
=================================================================
Total params: 4,963
Trainable params: 4,963
Non-trainable params: 0
_________________________________________________________________
None

The decoder shape is changing at some point. Can you help me in fixing this issue.

**Comment by ankonzoid** [comment]
The architecture given by the code currently gives exact matching for 100x100 images -- so for any other custom sizes you have to adjust the convolutional layer model parameters to match this (in `autoencoder.py`), or you could just resize your images into 100x100 images and use as is. Hope this helps.
