### ISSUE TITLE
Seems to require keras 2.2.0 

### ISSUE THREAD

**Issue by dgtlmoon** [ankonzoid/artificio#7]
I was getting the usual error on 2.4.0

https://stackoverflow.com/questions/49113140/importerror-cannot-import-name-obtain-input-shape-from-keras

```
$ python3 ./similar_images_TL.py 
Using TensorFlow backend.
Traceback (most recent call last):
  File "./similar_images_TL.py", line 17, in <module>
    from vgg19 import VGG19
  File "src/vgg19.py", line 26, in <module>
    from keras.applications.imagenet_utils import _obtain_input_shape
ImportError: cannot import name '_obtain_input_shape'
```

uninstalling and switching to 2.2.0 fixed it for me

`pip install keras==2.2.0`

so could be something missing from the documentation? thanks for the interesting project!

**Comment by hanumanraje** [comment]
I run the code on my local windows machine having 8 GB ram for 3000 images and it took around 1 hour. The same code I am running on CentOS server which has 188 GB ram for 13000 images but it has been running since more than 19 hours. Can somebody suggest me why this is happening? Is this OS problem?

**Comment by piaozhegao** [comment]
I think it may be  GPU problem. 
what kind of GPU was used in windows & CentOS ?

**Comment by hanumanraje** [comment]
i run it on CPU. it took 95% cpu utilization.we are not using GPU on both windows and CentOS. GPU is not available.is there any way to optimize this code  or any other solution if you have

**Comment by Ashishyelkar** [comment]
For your information,
Here are our hardware details,

Model name: Intel(R) Xeon(R) CPU     X5675  @ 3.07GHz
CPU op-mode(s):        32-bit, 64-bit
Core(s) per socket:    6
CPU(s):                24
CPU MHz:               1600.000
CPU max MHz:           3066.0000
CPU min MHz:           1600.0000

Let us know the system requirements provided is suitable for this code or recommendations from your side.

**Comment by dgtlmoon** [comment]
@hanumanraje @piaozhegao @Ashishyelkar it's incredibly frustrating when people hijack existing issues with completely a unrelated issue, please **_DO NOT_** do it, it ruins the community and destroys peoples motivation.

I'm closing this issue and opening a new one
