### ISSUE TITLE
I met this error when run

### ISSUE THREAD

**Issue by bemoregt** [ankonzoid/artificio#9]
Hi, @zdyang @ouzoh @ankonzoid 

I met this error when run similar_images_TL.py .

elxAir:similar_images_TL elx$ python3 similar_images_TL.py 
Using TensorFlow backend.
Traceback (most recent call last):
  File "similar_images_TL.py", line 17, in <module>
    from vgg19 import VGG19
  File "src/vgg19.py", line 26, in <module>
    from keras.applications.imagenet_utils import _obtain_input_shape
ImportError: cannot import name '_obtain_input_shape' from 'keras.applications.imagenet_utils' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/keras/applications/imagenet_utils.py)

What's wrong to me?

**Comment by rahulkishan-mobbed** [comment]
@bemoregt.. had the same error. refer [this](https://stackoverflow.com/questions/49113140/importerror-cannot-import-name-obtain-input-shape-from-keras) and try changing the module 
from keras.applications.imagenet_utils ...
to
from keras_applications.imagenet_utils.. here https://github.com/ankonzoid/artificio/blob/9398c0a180dc8eb0e1b6aa38adfb57e5a54f58b5/similar_images_TL/src/vgg19.py#L26

**Comment by bemoregt** [comment]
Hi, @rahulkishan-mobbed 

Thanks a lot !

**Comment by ankonzoid** [comment]
Sorry for late reply, use latest version of repo where I've changed everything to user tensorflow keras now (+ many more updates + cleaner code).
